name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'


jobs:
  urocmienie_testu:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: install build dependencies
      run: sudo apt-get install -y python3-venv
    - name: prepare python virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install pytest
    - name: run tests
      run: source venv/bin/activate && pytest
